include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: sofle_left
    shield: nice_view_adapter nice_view_battery
    artifact-name: sofle_left
  - board: sofle_right
    shield: nice_view_adapter nice_view_battery
    artifact-name: sofle_right
